### ISSUE TITLE
Events bug?

### ISSUE THREAD

**Issue by ExceptionDev** [ExceptionDev/Rick#28]
Not sure if anyone else experienced it. I don't see any complaints so far but it seems the bot sends multiple events if some event is set to true in x number of guilds. For example if a join event is enabled in 2 guilds and a user joins in guild X, the bot would send 2 join events in guild X. I guess the higher the number, the amount of events will be higher as well. That shouldn't be happening because if a guild enables auto respond that would lead to spam and rate limits.

**Comment by ExceptionDev** [comment]
Removed autorespond if possible

**Comment by ExceptionDev** [comment]
Removed AutoRespond because Tags = AutoRespond but nicer

**Comment by ExceptionDev** [comment]
Thanks to AntiTCB, Quantic and others for helping me out!
IT'S SOLVEDDD!

**Comment by ExceptionDev** [comment]
I'll probably consider adding auto respond back

**Comment by Yucked** [comment]
Nope.
It's all done.
